export const SHOPPER_URI = 'ui://matchrv/shopper-v1.html';
export const SHOPPER_HTML = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>MatchRV shopper</title><style>
:root{color-scheme:light dark;font:15px/1.5 system-ui;color:#142b2b;background:#f4fbfa}*{box-sizing:border-box}body{margin:0;padding:22px}header{display:flex;align-items:center;justify-content:space-between;gap:16px}h1{font-size:26px;margin:0}h2{font-size:18px;margin:0 0 8px}p{margin:6px 0}label{display:block;font-weight:600}input,select,button{font:inherit;padding:10px;border:1px solid #728f8f;border-radius:8px}input,select{background:transparent;color:inherit;width:100%}button{background:#075e63;color:white;cursor:pointer}button:disabled{opacity:.5;cursor:default}button:focus-visible,input:focus-visible{outline:3px solid #00a5b0;outline-offset:3px}form{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;align-items:end;margin:18px 0}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(255px,1fr));gap:12px}.card,.panel{border:1px solid #c2d8d8;border-radius:12px;background:#fff;padding:16px;margin:12px 0}.actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.actions label{font-weight:400}.actions input{width:auto}.price{font-size:22px;font-weight:700}.muted{color:#526868}.badge{font-size:13px;font-weight:600;color:#765200}#status{min-height:24px}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:left;border-bottom:1px solid #c2d8d8;padding:10px;vertical-align:top}.table-wrap{overflow:auto}footer{margin-top:22px;font-size:13px}.notice{border-left:3px solid #009da5;padding-left:12px}dl{display:grid;grid-template-columns:minmax(100px,1fr) 2fr;gap:8px}dd{margin:0}dt{color:#526868}@media(max-width:600px){body{padding:14px}form{grid-template-columns:1fr}header{align-items:start;flex-direction:column}}@media(prefers-color-scheme:dark){:root{background:#102326;color:#e8f4f3}.card,.panel{background:#183035;border-color:#476166}.muted,dt{color:#b2cccc}.badge{color:#ffce78}button{background:#087780}th,td{border-color:#476166}}
</style></head><body><header><div><h1>MatchRV</h1><p class="muted">Find the RV that fits your plans.</p></div><span>Inventory research</span></header>
<form id="search"><label>RV type<select id="rv-type"><option value="">Any type</option><option value="travel_trailer">Travel trailer</option><option value="fifth_wheel">Fifth wheel</option><option value="class_a">Class A</option><option value="class_b">Class B</option><option value="class_c">Class C</option><option value="toy_hauler">Toy hauler</option><option value="truck_camper">Truck camper</option></select></label><label>Maximum price ($)<input id="price" type="number" min="1" step="1"></label><label>Minimum sleeps<input id="sleeps" type="number" min="1" max="14" step="1"></label><label>Minimum length (ft)<input id="length-min" type="number" min="8" max="60" step="0.1"></label><label>Maximum length (ft)<input id="length-max" type="number" min="8" max="60" step="0.1"></label><label>Require bunks<select id="bunks"><option value="">No preference</option><option value="yes">Bunkhouse required</option></select></label><label>City and state, or state<input id="place" maxlength="80" placeholder="Tacoma, WA"></label><button id="search-button">Search inventory</button></form>
<p id="status" role="status" aria-live="polite">Waiting for MatchRV results from the conversation.</p>
<div class="actions"><button id="back" hidden>Back to results</button><button id="compare" disabled>Compare selected (0)</button></div>
<main id="content"></main><footer class="notice">Specifications and inventory can change. Unknown or inferred facts need verification. Tow-fit is planning guidance, not a safety determination. Dealer contact and purchases are not available in this release.</footer>
<script>
const content=document.getElementById('content'),status=document.getElementById('status'),compareButton=document.getElementById('compare'),back=document.getElementById('back');
const selected=new Set(),pending=new Map();let id=1,searchData=null,latestConstraints={},ready=false,busy=false;
function el(tag,text,cls){const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(cls)node.className=cls;return node;}
const known=v=>v===null||v===undefined?'Unknown':String(v);
const usd=v=>v===null||v===undefined?'Price unknown':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
function rpc(method,params){return new Promise((resolve,reject)=>{const key=id++;const timer=setTimeout(()=>{pending.delete(key);reject(new Error('MatchRV did not respond. Try again in the conversation.'));},30000);pending.set(key,{resolve,reject,timer});window.parent.postMessage({jsonrpc:'2.0',id:key,method,params},'*');});}
function payload(result){if(result?.isError)throw new Error(result.content?.find(c=>c.type==='text')?.text||'MatchRV request failed');if(result?.structuredContent)return result.structuredContent;const text=result?.content?.find(c=>c.type==='text')?.text;return text?JSON.parse(text):{};}
function selection(){compareButton.textContent='Compare selected ('+selected.size+')';compareButton.disabled=busy||selected.size<2;}
async function call(name,args){if(!ready)throw new Error('Open MatchRV in a compatible host to use these controls.');if(busy)return;busy=true;selection();document.getElementById('search-button').disabled=true;status.textContent='Loading MatchRV…';try{const result=await rpc('tools/call',{name,arguments:args});show(payload(result));}catch(e){status.textContent=e.message||'Request failed. Please try again.';}finally{busy=false;selection();document.getElementById('search-button').disabled=false;}}
function show(data){if(data.error){status.textContent=data.guidance||data.detail||data.error;return;}content.replaceChildren();back.hidden=!searchData;if(data.results){searchData=data;latestConstraints=data.appliedConstraints||{};document.getElementById('rv-type').value=latestConstraints.rvTypes?.length===1?latestConstraints.rvTypes[0]:'';document.getElementById('price').value=latestConstraints.priceMaxUsd??'';document.getElementById('sleeps').value=latestConstraints.sleepsMin??'';document.getElementById('length-min').value=latestConstraints.lengthMinFt??'';document.getElementById('length-max').value=latestConstraints.lengthMaxFt??'';document.getElementById('bunks').value=latestConstraints.mustHave?.includes('bunkhouse')?'yes':'';document.getElementById('place').value=latestConstraints.location?.place??'';selected.clear();back.hidden=true;selection();const total=data.funnel?.searched;status.textContent=data.results.length+' shown'+(total?' from '+total.toLocaleString()+' records':'')+'. '+(data.funnel?.verifiedMatches??0)+' verified matches; '+(data.funnel?.unverified??0)+' unverified.';if(data.coverage?.requested_area)content.append(el('p','Search area: '+data.coverage.requested_area+(data.coverage.scope==='state'?' (state-wide)':data.coverage.radius_miles?' within '+data.coverage.radius_miles+' miles':'')));if(!data.results.length)content.append(el('p',data.guidance||'No matching records. Change a requirement explicitly to search again.'));const cards=el('div',undefined,'cards');for(const row of data.results){const card=el('article',undefined,'card');card.append(el('h2',row.title),el('p',usd(row.price),'price'),el('p',row.dealer||'Dealer unknown','muted'),el('p','Length: '+known(row.lengthFt)+' ft · Sleeps: '+known(row.sleeps)+(row.sleepsConfirmed===false?' (inferred; confirm)':'')),el('p',row.verified?'Requested constraints verified from known facts':'Unverified — confirm missing facts','badge'));if(row.unknown?.length)card.append(el('p','Unknown: '+row.unknown.join(', ')));const actions=el('div',undefined,'actions'),details=el('button','View details');details.onclick=()=>call('get_rv',{unit_id:row.unit_id||row.id});const label=el('label'),check=el('input');check.type='checkbox';check.onchange=()=>{const key=row.unit_id||row.id;if(check.checked&&selected.size>=4){check.checked=false;status.textContent='Compare up to four RVs.';return;}check.checked?selected.add(key):selected.delete(key);selection();};label.append(check,document.createTextNode(' Compare'));actions.append(details,label);card.append(actions);cards.append(card);}content.append(cards);if(data.source)content.append(el('p',data.source,'muted'));return;}
if(data.unit){const u=data.unit;status.textContent='Listing details';const panel=el('section',undefined,'panel');panel.append(el('h2',u.title),el('p',usd(u.priceUsd?.value),'price'),el('p',[u.dealer?.name,u.dealer?.city,u.dealer?.state].filter(Boolean).join(', ')));const dl=el('dl');for(const [label,key,suffix] of [['Length','lengthFt',' ft'],['Sleeps','sleeps',''],['Dry weight','dryWeightLbs',' lb'],['GVWR','gvwrLbs',' lb'],['Bunkhouse','bunkhouse',''],['Slides','slideouts','']]){const f=u[key];dl.append(el('dt',label),el('dd',known(f?.value)+(f?.value!=null?suffix:'')+(f?.source?' · '+f.source:'')));}panel.append(dl);if(u.provenance?.lastSeenAt)panel.append(el('p','Last seen: '+u.provenance.lastSeenAt,'muted'));if(data.dataset?.builtAt)panel.append(el('p','Snapshot built: '+data.dataset.builtAt,'muted'));const label=el('label','Tow vehicle and actual rating if known'),input=el('input');input.placeholder='Ford F-150 rated 8,000 lb';input.maxLength=120;const button=el('button','Check tow considerations');button.onclick=()=>{if(input.value.trim().length<2){status.textContent='Enter your vehicle first.';return;}call('evaluate_tow_fit',{vehicle:input.value.trim(),unit_ids:[u.id]});};panel.append(label,input,button);content.append(panel);return;}
if(data.comparison){status.textContent='Comparison — unknown values stay unknown';const wrap=el('div',undefined,'table-wrap'),table=el('table'),head=el('tr');head.append(el('th','Specification'));for(const t of data.comparison.titles||[])head.append(el('th',t));table.append(head);for(const row of data.comparison.rows||[]){const tr=el('tr');tr.append(el('th',row.spec+(row.unit?' ('+row.unit+')':'')));row.values.forEach((v,n)=>tr.append(el('td',known(v)+(row.sources?.[n]?' · '+row.sources[n]:''))));table.append(tr);}wrap.append(table);content.append(wrap);for(const note of data.comparison.unknownNotes||[])content.append(el('p',typeof note==='string'?note:JSON.stringify(note),'muted'));return;}
if(data.fits){status.textContent='Tow-fit considerations';for(const fit of data.fits){const panel=el('section',undefined,'panel');panel.append(el('h2',fit.title||'RV'),el('p',known(fit.verdict),'badge'),el('p',fit.detail||'Verify missing weight and vehicle ratings.'));content.append(panel);}for(const caveat of data.resolution?.caveats||[])content.append(el('p',caveat));content.append(el('p',data.safetyNotice||'Verify exact ratings before towing.','notice'));return;}status.textContent='No displayable MatchRV data returned.';}
window.addEventListener('message',event=>{if(event.source!==window.parent)return;const m=event.data;if(!m||m.jsonrpc!=='2.0')return;if(m.id!==undefined&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);return;}if(m.method==='ui/notifications/tool-result'){try{show(payload(m.params));}catch(e){status.textContent=e.message;}}});
document.getElementById('search').onsubmit=event=>{event.preventDefault();const constraints={...latestConstraints};const type=document.getElementById('rv-type').value,location=document.getElementById('place').value.trim();if(type)constraints.rvTypes=[type];else delete constraints.rvTypes;for(const [field,key] of [['price','priceMaxUsd'],['sleeps','sleepsMin'],['length-min','lengthMinFt'],['length-max','lengthMaxFt']]){const value=document.getElementById(field).value;if(value)constraints[key]=Number(value);else delete constraints[key];}const mustHave=(constraints.mustHave||[]).filter(f=>f!=='bunkhouse');if(document.getElementById('bunks').value==='yes')mustHave.push('bunkhouse');if(mustHave.length)constraints.mustHave=mustHave;else delete constraints.mustHave;if(location)constraints.location={place:location,radiusMiles:latestConstraints.location?.radiusMiles??150};else delete constraints.location;if(constraints.lengthMinFt&&constraints.lengthMaxFt&&constraints.lengthMinFt>constraints.lengthMaxFt){status.textContent='Minimum length must not exceed maximum length.';return;}call('search_rvs',{constraints,limit:6});};compareButton.onclick=()=>call('compare_rvs',{unit_ids:[...selected],constraints:latestConstraints});back.onclick=()=>{if(searchData)show(searchData);};
rpc('ui/initialize',{appInfo:{name:'matchrv-shopper',version:'0.1.0'},appCapabilities:{availableDisplayModes:['fullscreen']},protocolVersion:'2026-01-26'}).then(()=>{ready=true;window.parent.postMessage({jsonrpc:'2.0',method:'ui/notifications/initialized',params:{}},'*');}).catch(()=>{status.textContent='Host connection unavailable. Continue using MatchRV in the conversation.';});
</script></body></html>`;
