import { Link } from "wouter";
import { BrandLayout } from "@/components/brand-layout";
import { SEO } from "@/components/seo";

export function About() {
  return <BrandLayout><SEO title="About Jonathan Kitchel, Founder of MatchRV" description="Meet Jonathan Kitchel, the RV industry professional who founded and built MatchRV to help dealerships make their inventory easier for AI shoppers to understand." canonical="/about"/>
    <section className="brand-container brand-section"><p className="brand-eyebrow">The person behind MatchRV</p><h1>Built from experience.<br/>Built by Jonathan.</h1>
      <div className="founder-grid"><div className="founder-photo-placeholder" role="img" aria-label="Founder portrait coming soon"><span>JK</span><p>Jonathan Kitchel</p><small>Founder portrait coming soon</small></div>
      <article><h2>Jonathan Kitchel</h2><p className="brand-eyebrow">Founder &amp; builder · MatchRV</p><p className="brand-lead">I built MatchRV to connect the realities of the RV business with the way customers are starting to shop.</p><p>My background includes eight years at Poulsbo RV. Working in the industry showed me how much a good RV match depends on clear information: budget, sleeping capacity, weight, length, equipment, and how someone plans to travel.</p><p>Those details matter to a person on the lot. They also matter when a shopper asks an AI assistant for help. Missing or unclear inventory information makes the search harder before a customer ever contacts a dealership.</p><p>I founded and built MatchRV around that problem. The AI Visibility Report helps dealerships see what their inventory data communicates, what is missing, and what to improve. RV Outfitter brings the same focus on clear information to the shopping experience.</p></article></div>
      <div className="coverage-grid brand-section"><article className="coverage-card"><h3>A person behind the work</h3><p>Jonathan is the founder and builder of MatchRV. Your report conversation starts with the person responsible for the product.</p></article><article className="coverage-card"><h3>Evidence before promises</h3><p>Counts, dated observations, and clear limitations come before scores. Reports identify practical improvements without promising AI rankings.</p></article><article className="coverage-card"><h3>Built for the RV industry</h3><p>The work centers on the inventory details dealerships publish and the real questions shoppers ask.</p></article></div>
      <div className="report-bottom"><h2>See the work. Meet the builder.</h2><p>Explore completed audit examples, then talk through what a report could cover for your dealership.</p><Link className="brand-button" href="/visibility-report">View real report examples →</Link> <Link className="brand-button" href="/book">Book a call →</Link></div>
    </section></BrandLayout>;
}
