import { db, campgroundsTable } from "@workspace/db";

const campgrounds = [
  // Washington
  {
    name: "Deception Pass State Park",
    description: "Washington's most visited state park featuring dramatic bridges, saltwater beaches, and dense forest camping near Whidbey Island.",
    state: "WA", city: "Oak Harbor",
    lat: 48.4019, lon: -122.6449,
    hookupType: "water_electric", maxRvLength: 40, totalSites: 167,
    nightlyRateMin: 35, nightlyRateMax: 50,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["dump station", "showers", "flush toilets", "playground", "boat launch"],
    campgroundType: "state", imageUrl: null, phone: "360-675-2417",
  },
  {
    name: "Lake Wenatchee State Park",
    description: "Surrounded by Cascade mountains with a beautiful alpine lake, perfect for RVers seeking boating, swimming, and hiking adventures.",
    state: "WA", city: "Leavenworth",
    lat: 47.8127, lon: -120.7358,
    hookupType: "water_electric", maxRvLength: 50, totalSites: 197,
    nightlyRateMin: 30, nightlyRateMax: 45,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["dump station", "showers", "boat launch", "swimming beach", "playground"],
    campgroundType: "state", imageUrl: null, phone: "509-763-3101",
  },
  {
    name: "Steamboat Rock State Park",
    description: "A stunning basalt butte rises 800 feet above Banks Lake in the Columbia Plateau. Excellent fishing, water sports, and stargazing.",
    state: "WA", city: "Electric City",
    lat: 47.8739, lon: -119.1019,
    hookupType: "full", maxRvLength: 60, totalSites: 136,
    nightlyRateMin: 35, nightlyRateMax: 55,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["full hookups", "dump station", "showers", "boat launch", "swimming area"],
    campgroundType: "state", imageUrl: null, phone: "509-633-1304",
  },
  {
    name: "Fort Worden State Park",
    description: "Historic Victorian-era military fort turned state park on the Olympic Peninsula with beach access, lighthouse, and full-service camping.",
    state: "WA", city: "Port Townsend",
    lat: 48.1340, lon: -122.7589,
    hookupType: "full", maxRvLength: 50, totalSites: 80,
    nightlyRateMin: 40, nightlyRateMax: 60,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["full hookups", "dump station", "showers", "beach access", "conference center"],
    campgroundType: "state", imageUrl: null, phone: "360-344-4431",
  },
  {
    name: "Moran State Park",
    description: "Orcas Island gem with four lakes, a volcanic summit, and extensive trails. Accessible by Washington State Ferry from Anacortes.",
    state: "WA", city: "Eastsound",
    lat: 48.6558, lon: -122.8337,
    hookupType: "water_electric", maxRvLength: 45, totalSites: 151,
    nightlyRateMin: 30, nightlyRateMax: 45,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["dump station", "showers", "boat launch", "swimming", "hiking"],
    campgroundType: "state", imageUrl: null, phone: "360-376-2326",
  },
  {
    name: "Sequim Bay State Park",
    description: "Located in the Olympic Peninsula's 'banana belt,' this protected bay offers calm water boating and 270 days of sunshine per year.",
    state: "WA", city: "Sequim",
    lat: 48.0345, lon: -123.0331,
    hookupType: "water_electric", maxRvLength: 35, totalSites: 86,
    nightlyRateMin: 25, nightlyRateMax: 40,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["dump station", "showers", "boat launch", "hiking trails"],
    campgroundType: "state", imageUrl: null, phone: "360-683-4235",
  },
  {
    name: "Pacific Beach State Park",
    description: "Miles of wild Pacific Ocean beach right outside your door. Dig for razor clams and watch dramatic Pacific sunsets year-round.",
    state: "WA", city: "Pacific Beach",
    lat: 47.2082, lon: -124.2036,
    hookupType: "water_electric", maxRvLength: 40, totalSites: 64,
    nightlyRateMin: 30, nightlyRateMax: 45,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["dump station", "showers", "ocean beach", "razor clam digging"],
    campgroundType: "state", imageUrl: null, phone: "360-276-4297",
  },
  {
    name: "Conconully State Park",
    description: "Twin lakes in the Okanogan Highlands offer swimming, boating, and great fishing. Gateway to the Methow Valley.",
    state: "WA", city: "Conconully",
    lat: 48.5597, lon: -119.7489,
    hookupType: "water_electric", maxRvLength: 35, totalSites: 81,
    nightlyRateMin: 25, nightlyRateMax: 40,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["dump station", "showers", "boat launch", "swimming beach"],
    campgroundType: "state", imageUrl: null, phone: "509-826-7408",
  },
  {
    name: "Icicle Creek Campground",
    description: "National Forest campground in Tumwater Canyon along Icicle Creek, near Leavenworth. Excellent hiking and rock climbing access.",
    state: "WA", city: "Leavenworth",
    lat: 47.5956, lon: -120.8009,
    hookupType: "dry", maxRvLength: 30, totalSites: 63,
    nightlyRateMin: 22, nightlyRateMax: 22,
    bookingUrl: "https://www.recreation.gov/camping/gateways/1430",
    amenities: ["vault toilets", "creek access", "hiking", "rock climbing nearby"],
    campgroundType: "federal", imageUrl: null, phone: null,
  },
  {
    name: "Yakima Sportsman State Park",
    description: "Oasis of green along the Yakima River in semi-arid eastern Washington. Great base camp for wine country exploration.",
    state: "WA", city: "Yakima",
    lat: 46.6204, lon: -120.4785,
    hookupType: "full", maxRvLength: 60, totalSites: 37,
    nightlyRateMin: 35, nightlyRateMax: 50,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["full hookups", "dump station", "showers", "fishing", "bird watching"],
    campgroundType: "state", imageUrl: null, phone: "509-575-2774",
  },
  {
    name: "Sun Lakes-Dry Falls State Park",
    description: "Camp at the base of one of the world's largest prehistoric waterfalls. Ancient dry coulees provide dramatic, otherworldly scenery.",
    state: "WA", city: "Coulee City",
    lat: 47.5863, lon: -119.3742,
    hookupType: "full", maxRvLength: 60, totalSites: 193,
    nightlyRateMin: 30, nightlyRateMax: 50,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["full hookups", "dump station", "showers", "boat launch", "golf course", "interpretive center"],
    campgroundType: "state", imageUrl: null, phone: "509-632-5583",
  },
  {
    name: "Silver Lake Campground",
    description: "Forest Service campground near Mount St. Helens with a beautiful volcanic lake backdrop. Close to Mount St. Helens visitor center.",
    state: "WA", city: "Cougar",
    lat: 46.0132, lon: -122.3254,
    hookupType: "dry", maxRvLength: 32, totalSites: 94,
    nightlyRateMin: 18, nightlyRateMax: 20,
    bookingUrl: "https://www.recreation.gov",
    amenities: ["vault toilets", "boat launch", "fishing", "Mt. St. Helens views"],
    campgroundType: "federal", imageUrl: null, phone: null,
  },
  // Oregon
  {
    name: "Beverly Beach State Park",
    description: "A mile of Pacific beach with a scenic cove. Watch gray whales migrate past, explore tide pools, and enjoy Oregon's stunning coast.",
    state: "OR", city: "Newport",
    lat: 44.7482, lon: -124.0625,
    hookupType: "full", maxRvLength: 65, totalSites: 279,
    nightlyRateMin: 29, nightlyRateMax: 52,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "ocean beach", "whale watching"],
    campgroundType: "state", imageUrl: null, phone: "541-265-9278",
  },
  {
    name: "Cape Lookout State Park",
    description: "A forested headland jutting 2 miles into the Pacific offers whale watching and access to gorgeous Three Capes Scenic Route.",
    state: "OR", city: "Tillamook",
    lat: 45.3517, lon: -123.9754,
    hookupType: "full", maxRvLength: 60, totalSites: 250,
    nightlyRateMin: 26, nightlyRateMax: 52,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "beach access", "hiking trails"],
    campgroundType: "state", imageUrl: null, phone: "503-842-4981",
  },
  {
    name: "Bullards Beach State Park",
    description: "Near the Bandon Lighthouse and South Slough National Estuarine Reserve. Great crabbing, clamming, and horseback riding on the beach.",
    state: "OR", city: "Bandon",
    lat: 43.1531, lon: -124.4217,
    hookupType: "full", maxRvLength: 65, totalSites: 192,
    nightlyRateMin: 29, nightlyRateMax: 52,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "lighthouse", "beach access", "horse camp"],
    campgroundType: "state", imageUrl: null, phone: "541-347-2209",
  },
  {
    name: "Harris Beach State Park",
    description: "Oregon's southernmost state park campground, with rocky sea stacks, tidepools, and some of the warmest waters on the Oregon coast.",
    state: "OR", city: "Brookings",
    lat: 42.0545, lon: -124.3085,
    hookupType: "full", maxRvLength: 50, totalSites: 151,
    nightlyRateMin: 29, nightlyRateMax: 55,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "tidepools", "beach access"],
    campgroundType: "state", imageUrl: null, phone: "541-469-2021",
  },
  {
    name: "Honeyman Memorial State Park",
    description: "Dramatic sand dunes, freshwater Cleawox Lake, and dense spruce forests make this one of Oregon's most popular destinations.",
    state: "OR", city: "Florence",
    lat: 44.0066, lon: -124.1049,
    hookupType: "full", maxRvLength: 60, totalSites: 381,
    nightlyRateMin: 24, nightlyRateMax: 52,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "sand dunes", "swimming lake", "ATV access"],
    campgroundType: "state", imageUrl: null, phone: "541-997-3641",
  },
  {
    name: "Wallowa Lake State Park",
    description: "At the foot of the Eagle Cap Wilderness, this glacially carved lake offers boating, fishing, a tramway to 8,150 feet, and stunning peaks.",
    state: "OR", city: "Joseph",
    lat: 45.2735, lon: -117.2129,
    hookupType: "full", maxRvLength: 60, totalSites: 121,
    nightlyRateMin: 24, nightlyRateMax: 52,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "boat launch", "marina", "tramway nearby"],
    campgroundType: "state", imageUrl: null, phone: "541-432-4185",
  },
  {
    name: "Tumalo State Park",
    description: "Just 5 miles from downtown Bend along the Deschutes River. Ideal base camp for high desert hiking, mountain biking, and craft beer.",
    state: "OR", city: "Bend",
    lat: 44.1021, lon: -121.3556,
    hookupType: "full", maxRvLength: 44, totalSites: 88,
    nightlyRateMin: 28, nightlyRateMax: 50,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "river access", "fishing", "group sites"],
    campgroundType: "state", imageUrl: null, phone: "541-382-3586",
  },
  {
    name: "LaPine State Park",
    description: "Deep in Deschutes National Forest with old-growth ponderosa pines, the Deschutes River, and access to lava fields and Newberry Volcano.",
    state: "OR", city: "La Pine",
    lat: 43.6749, lon: -121.4996,
    hookupType: "full", maxRvLength: 55, totalSites: 145,
    nightlyRateMin: 24, nightlyRateMax: 52,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "river fishing", "hiking"],
    campgroundType: "state", imageUrl: null, phone: "541-536-2428",
  },
  {
    name: "Detroit Lake State Recreation Area",
    description: "A large reservoir in the Cascade foothills with warm water, excellent fishing for rainbow trout and kokanee, and mountain views.",
    state: "OR", city: "Detroit",
    lat: 44.7288, lon: -122.1536,
    hookupType: "full", maxRvLength: 60, totalSites: 309,
    nightlyRateMin: 24, nightlyRateMax: 52,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "marina", "boat launch", "swimming"],
    campgroundType: "state", imageUrl: null, phone: "503-854-3346",
  },
  {
    name: "Smith Rock State Park Bivy",
    description: "World-renowned rock climbing destination in Oregon's high desert. The bivy camping area puts you steps from some of America's best sport climbing.",
    state: "OR", city: "Terrebonne",
    lat: 44.3676, lon: -121.1421,
    hookupType: "dry", maxRvLength: 35, totalSites: 25,
    nightlyRateMin: 7, nightlyRateMax: 7,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["flush toilets", "running water", "rock climbing", "hiking", "bird watching"],
    campgroundType: "state", imageUrl: null, phone: "541-548-7501",
  },
  {
    name: "Champoeg State Heritage Area",
    description: "Historic site where Oregon's first provisional government was formed in 1843. Quiet Willamette Valley camping with rich Pacific Northwest history.",
    state: "OR", city: "Newberg",
    lat: 45.2468, lon: -122.8836,
    hookupType: "full", maxRvLength: 60, totalSites: 48,
    nightlyRateMin: 24, nightlyRateMax: 52,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "museum", "hiking trails", "wine country nearby"],
    campgroundType: "state", imageUrl: null, phone: "503-678-1251",
  },
  {
    name: "Shore Acres State Park (Bastendorff Beach CG)",
    description: "Adjacent to Shore Acres' spectacular ocean gardens and dramatic cliffs, this campground is steps from the rugged southern Oregon coast.",
    state: "OR", city: "Coos Bay",
    lat: 43.3692, lon: -124.3789,
    hookupType: "water_electric", maxRvLength: 45, totalSites: 63,
    nightlyRateMin: 22, nightlyRateMax: 40,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["dump station", "showers", "beach access", "botanical gardens nearby", "ocean views"],
    campgroundType: "state", imageUrl: null, phone: "541-888-2472",
  },
  // Idaho
  {
    name: "Ponderosa State Park",
    description: "A forested peninsula jutting into Payette Lake near McCall with stunning mountain lake views and access to excellent outdoor recreation.",
    state: "ID", city: "McCall",
    lat: 44.9196, lon: -116.0878,
    hookupType: "full", maxRvLength: 60, totalSites: 170,
    nightlyRateMin: 25, nightlyRateMax: 45,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "boat launch", "swimming beach", "visitor center"],
    campgroundType: "state", imageUrl: null, phone: "208-634-2164",
  },
  {
    name: "Redfish Lake Campground",
    description: "One of Idaho's most spectacular campgrounds at 6,548 feet elevation in the Sawtooth NRA, with iconic mountain reflections in the lake.",
    state: "ID", city: "Stanley",
    lat: 44.1515, lon: -114.9025,
    hookupType: "dry", maxRvLength: 35, totalSites: 133,
    nightlyRateMin: 20, nightlyRateMax: 24,
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/233947",
    amenities: ["flush toilets", "showers", "boat launch", "swimming beach", "visitor center", "lodge nearby"],
    campgroundType: "federal", imageUrl: null, phone: "208-774-3376",
  },
  {
    name: "Henrys Lake State Park",
    description: "World-class cutthroat-rainbow trout hybrid fishing just outside Yellowstone's west entrance. High-altitude lake with big sky country views.",
    state: "ID", city: "Island Park",
    lat: 44.6046, lon: -111.4197,
    hookupType: "full", maxRvLength: 60, totalSites: 55,
    nightlyRateMin: 22, nightlyRateMax: 40,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "boat launch", "fishing"],
    campgroundType: "state", imageUrl: null, phone: "208-558-7532",
  },
  {
    name: "Farragut State Park",
    description: "Idaho's largest state park on the shores of Lake Pend Oreille — one of the deepest and most beautiful lakes in North America.",
    state: "ID", city: "Athol",
    lat: 47.9499, lon: -116.5761,
    hookupType: "full", maxRvLength: 60, totalSites: 221,
    nightlyRateMin: 20, nightlyRateMax: 35,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "boat launch", "beach", "shooting range", "archery"],
    campgroundType: "state", imageUrl: null, phone: "208-683-2425",
  },
  {
    name: "Three Island Crossing State Park",
    description: "Where Oregon Trail emigrants forded the Snake River. Interpretive programs and Oregon Trail history meet great fishing and wildlife viewing.",
    state: "ID", city: "Glenns Ferry",
    lat: 42.9492, lon: -115.3094,
    hookupType: "full", maxRvLength: 60, totalSites: 101,
    nightlyRateMin: 20, nightlyRateMax: 35,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "museum", "fishing", "Oregon Trail history"],
    campgroundType: "state", imageUrl: null, phone: "208-366-2394",
  },
  {
    name: "Bear Lake State Park",
    description: "The 'Caribbean of the Rockies' — Bear Lake's striking turquoise water from suspended calcium carbonate is unlike anything in the PNW.",
    state: "ID", city: "Saint Charles",
    lat: 42.0997, lon: -111.3788,
    hookupType: "water_electric", maxRvLength: 45, totalSites: 48,
    nightlyRateMin: 22, nightlyRateMax: 35,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["dump station", "showers", "swimming beach", "boat launch", "fishing"],
    campgroundType: "state", imageUrl: null, phone: "208-945-2565",
  },
  {
    name: "Bruneau Dunes State Park",
    description: "North America's tallest single-structured sand dune — 470 feet high. Outstanding stargazing at the park's observatory after dark.",
    state: "ID", city: "Bruneau",
    lat: 42.8886, lon: -115.7963,
    hookupType: "full", maxRvLength: 60, totalSites: 94,
    nightlyRateMin: 18, nightlyRateMax: 32,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "observatory", "sandboarding", "fishing"],
    campgroundType: "state", imageUrl: null, phone: "208-366-7919",
  },
  {
    name: "Hells Gate State Park",
    description: "Perched above the Snake River canyon near Lewiston, Idaho's lowest elevation point. Jet boat tours into Hells Canyon launch from here.",
    state: "ID", city: "Lewiston",
    lat: 46.3822, lon: -117.0524,
    hookupType: "full", maxRvLength: 65, totalSites: 93,
    nightlyRateMin: 20, nightlyRateMax: 35,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "marina", "boat launch", "jet boat tours"],
    campgroundType: "state", imageUrl: null, phone: "208-799-5015",
  },
  {
    name: "Round Lake State Park",
    description: "A quiet, small lake surrounded by second-growth western red cedar and western white pine near Sandpoint in the Idaho Panhandle.",
    state: "ID", city: "Sagle",
    lat: 48.0854, lon: -116.5745,
    hookupType: "dry", maxRvLength: 30, totalSites: 53,
    nightlyRateMin: 16, nightlyRateMax: 28,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["dump station", "flush toilets", "swimming beach", "fishing", "non-motorized boating"],
    campgroundType: "state", imageUrl: null, phone: "208-263-3489",
  },
  {
    name: "Lucky Peak State Park",
    description: "Three separate reservoir areas near Boise offer water skiing, wakeboarding, swimming, and a great escape from the city heat.",
    state: "ID", city: "Boise",
    lat: 43.5399, lon: -116.0403,
    hookupType: "dry", maxRvLength: 40, totalSites: 37,
    nightlyRateMin: 15, nightlyRateMax: 25,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["vault toilets", "swimming beach", "boat launch", "water skiing", "fishing"],
    campgroundType: "state", imageUrl: null, phone: "208-334-2432",
  },
  // Montana
  {
    name: "Apgar Campground – Glacier National Park",
    description: "The most accessible campground in Glacier NP, on the shores of Lake McDonald with stunning views of surrounding peaks and clear glacial water.",
    state: "MT", city: "West Glacier",
    lat: 48.5004, lon: -113.9858,
    hookupType: "dry", maxRvLength: 21, totalSites: 194,
    nightlyRateMin: 20, nightlyRateMax: 20,
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/232493",
    amenities: ["flush toilets", "dump station", "camp store", "ranger programs", "boat rentals", "shuttle access"],
    campgroundType: "federal", imageUrl: null, phone: "406-888-7800",
  },
  {
    name: "Many Glacier Campground – Glacier National Park",
    description: "The backcountry heart of Glacier, surrounded by peaks, glaciers, and wildlife. Frequent grizzly bear sightings and world-class hiking.",
    state: "MT", city: "Babb",
    lat: 48.7974, lon: -113.6596,
    hookupType: "dry", maxRvLength: 21, totalSites: 109,
    nightlyRateMin: 20, nightlyRateMax: 23,
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/232492",
    amenities: ["flush toilets", "dump station", "ranger programs", "boat tours", "hiking access"],
    campgroundType: "federal", imageUrl: null, phone: "406-888-7800",
  },
  {
    name: "St. Mary Campground – Glacier National Park",
    description: "The east side gateway to Going-to-the-Sun Road with sweeping prairie-meets-mountain scenery and spectacular evening alpenglow on the peaks.",
    state: "MT", city: "St. Mary",
    lat: 48.7459, lon: -113.4322,
    hookupType: "dry", maxRvLength: 21, totalSites: 148,
    nightlyRateMin: 20, nightlyRateMax: 23,
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/232494",
    amenities: ["flush toilets", "dump station", "camp store", "ranger programs", "Going-to-the-Sun access"],
    campgroundType: "federal", imageUrl: null, phone: "406-888-7800",
  },
  {
    name: "Glacier Campground",
    description: "Popular private campground just outside Glacier NP's west entrance with easy park access, full hookups, and a friendly host community.",
    state: "MT", city: "West Glacier",
    lat: 48.5007, lon: -113.9823,
    hookupType: "full", maxRvLength: 70, totalSites: 160,
    nightlyRateMin: 35, nightlyRateMax: 65,
    bookingUrl: "https://www.glaciercampground.com",
    amenities: ["full hookups", "dump station", "showers", "camp store", "laundry", "fire rings"],
    campgroundType: "private", imageUrl: null, phone: "406-387-5689",
  },
  {
    name: "Flathead Lake State Park – Wayfarers",
    description: "On the eastern shore of massive Flathead Lake — the largest natural freshwater lake west of the Mississippi — with mountain backdrop.",
    state: "MT", city: "Bigfork",
    lat: 47.9820, lon: -113.9700,
    hookupType: "dry", maxRvLength: 40, totalSites: 30,
    nightlyRateMin: 18, nightlyRateMax: 28,
    bookingUrl: "https://stateparks.mt.gov",
    amenities: ["vault toilets", "boat launch", "swimming", "fishing", "picnic areas"],
    campgroundType: "state", imageUrl: null, phone: "406-837-4196",
  },
  {
    name: "Whitefish Lake State Park",
    description: "Minutes from the charming resort town of Whitefish, with easy access to Glacier NP and Big Mountain ski resort. Perfect base camp.",
    state: "MT", city: "Whitefish",
    lat: 48.4369, lon: -114.3779,
    hookupType: "dry", maxRvLength: 40, totalSites: 25,
    nightlyRateMin: 18, nightlyRateMax: 28,
    bookingUrl: "https://stateparks.mt.gov",
    amenities: ["flush toilets", "boat launch", "swimming beach", "fishing", "downtown Whitefish nearby"],
    campgroundType: "state", imageUrl: null, phone: "406-862-3991",
  },
  {
    name: "Missouri Headwaters State Park",
    description: "Where the Jefferson, Madison, and Gallatin rivers converge to form the mighty Missouri River, just as Lewis & Clark discovered in 1805.",
    state: "MT", city: "Three Forks",
    lat: 45.9306, lon: -111.5042,
    hookupType: "dry", maxRvLength: 45, totalSites: 27,
    nightlyRateMin: 12, nightlyRateMax: 18,
    bookingUrl: "https://stateparks.mt.gov",
    amenities: ["vault toilets", "interpretive center", "fishing", "hiking", "Lewis & Clark history"],
    campgroundType: "state", imageUrl: null, phone: "406-285-3610",
  },
  {
    name: "Lewis & Clark Caverns State Park",
    description: "Montana's first state park features one of the largest limestone cave systems in the Northwest, plus the Gallatin River valley setting.",
    state: "MT", city: "Whitehall",
    lat: 45.6434, lon: -112.0817,
    hookupType: "dry", maxRvLength: 35, totalSites: 40,
    nightlyRateMin: 15, nightlyRateMax: 25,
    bookingUrl: "https://stateparks.mt.gov",
    amenities: ["flush toilets", "cave tours", "visitor center", "river access", "hiking"],
    campgroundType: "state", imageUrl: null, phone: "406-287-3541",
  },
  {
    name: "Polson Motorcoach & RV Resort",
    description: "Full-service resort on Flathead Lake with paved sites, stunning mountain lake views, close to the Polson golf course and waterfront.",
    state: "MT", city: "Polson",
    lat: 47.6939, lon: -114.1615,
    hookupType: "full", maxRvLength: 75, totalSites: 112,
    nightlyRateMin: 45, nightlyRateMax: 75,
    bookingUrl: "https://www.polsonrvresort.com",
    amenities: ["full hookups", "dump station", "showers", "pool", "laundry", "club house", "Flathead Lake views"],
    campgroundType: "private", imageUrl: null, phone: "406-883-2375",
  },
  {
    name: "Madison Arm Resort",
    description: "On Hebgen Lake just miles from Yellowstone's west entrance, this resort offers the best of both worlds: resort amenities and national park access.",
    state: "MT", city: "West Yellowstone",
    lat: 44.6542, lon: -111.0985,
    hookupType: "full", maxRvLength: 70, totalSites: 80,
    nightlyRateMin: 40, nightlyRateMax: 70,
    bookingUrl: "https://www.madisonarmresort.com",
    amenities: ["full hookups", "dump station", "showers", "marina", "boat rentals", "Yellowstone access"],
    campgroundType: "private", imageUrl: null, phone: "406-646-9328",
  },
  {
    name: "Yellowstone's Edge RV Park",
    description: "Along the Yellowstone River near Livingston, MT, this park offers stunning Absaroka Range views and easy access to the Paradise Valley.",
    state: "MT", city: "Livingston",
    lat: 45.7023, lon: -110.5573,
    hookupType: "full", maxRvLength: 70, totalSites: 81,
    nightlyRateMin: 38, nightlyRateMax: 60,
    bookingUrl: "https://www.yellowstonesedge.com",
    amenities: ["full hookups", "dump station", "showers", "laundry", "river access", "fishing"],
    campgroundType: "private", imageUrl: null, phone: "406-333-4036",
  },
  {
    name: "Missoula KOA",
    description: "Family-friendly KOA on the Clark Fork River near vibrant Missoula, with easy access to the University of Montana, hiking, and craft breweries.",
    state: "MT", city: "Missoula",
    lat: 46.8527, lon: -113.9840,
    hookupType: "full", maxRvLength: 70, totalSites: 170,
    nightlyRateMin: 40, nightlyRateMax: 65,
    bookingUrl: "https://koa.com/campgrounds/missoula",
    amenities: ["full hookups", "dump station", "showers", "pool", "laundry", "cabins", "bike rentals"],
    campgroundType: "private", imageUrl: null, phone: "406-549-0881",
  },
  {
    name: "Bozeman KOA",
    description: "Full-service KOA between Bozeman and the Bridger Mountains, close to ski resorts, whitewater rafting, fly fishing, and Yellowstone access.",
    state: "MT", city: "Bozeman",
    lat: 45.6770, lon: -111.0429,
    hookupType: "full", maxRvLength: 70, totalSites: 115,
    nightlyRateMin: 42, nightlyRateMax: 68,
    bookingUrl: "https://koa.com/campgrounds/bozeman",
    amenities: ["full hookups", "dump station", "showers", "pool", "laundry", "playground", "dog park"],
    campgroundType: "private", imageUrl: null, phone: "406-587-3030",
  },
  {
    name: "Beartooth Hideaway RV Park",
    description: "In Red Lodge at the foot of the spectacular Beartooth Highway — the most beautiful drive in America according to Charles Kuralt.",
    state: "MT", city: "Red Lodge",
    lat: 45.1855, lon: -109.2433,
    hookupType: "full", maxRvLength: 65, totalSites: 70,
    nightlyRateMin: 38, nightlyRateMax: 58,
    bookingUrl: "https://www.beartoothrvpark.com",
    amenities: ["full hookups", "dump station", "showers", "laundry", "Beartooth Highway access"],
    campgroundType: "private", imageUrl: null, phone: "406-446-2575",
  },
  {
    name: "Great Falls KOA",
    description: "Central Montana hub along the Missouri River, near the Lewis & Clark National Historic Trail Interpretive Center and Giant Springs State Park.",
    state: "MT", city: "Great Falls",
    lat: 47.4882, lon: -111.2799,
    hookupType: "full", maxRvLength: 70, totalSites: 138,
    nightlyRateMin: 38, nightlyRateMax: 60,
    bookingUrl: "https://koa.com/campgrounds/great-falls",
    amenities: ["full hookups", "dump station", "showers", "pool", "laundry", "Lewis & Clark history"],
    campgroundType: "private", imageUrl: null, phone: "406-727-3191",
  },
  {
    name: "Emigrant Springs State Heritage Area",
    description: "Historic rest stop on the Oregon Trail in the Blue Mountains, where emigrants camped and rested on their westward journey to the Willamette Valley.",
    state: "OR", city: "Meacham",
    lat: 45.5296, lon: -118.4113,
    hookupType: "full", maxRvLength: 50, totalSites: 51,
    nightlyRateMin: 19, nightlyRateMax: 40,
    bookingUrl: "https://oregonstateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "Oregon Trail history", "hiking"],
    campgroundType: "state", imageUrl: null, phone: "541-983-2277",
  },
  // Additional Washington
  {
    name: "Pearrygin Lake State Park",
    description: "The gateway to the Methow Valley's world-class mountain biking and cross-country skiing, set on a scenic lake in the Okanogan Highlands.",
    state: "WA", city: "Winthrop",
    lat: 48.5031, lon: -120.1397,
    hookupType: "full", maxRvLength: 60, totalSites: 167,
    nightlyRateMin: 30, nightlyRateMax: 50,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["full hookups", "dump station", "showers", "swimming beach", "boat launch", "fishing"],
    campgroundType: "state", imageUrl: null, phone: "509-996-2370",
  },
  {
    name: "Kalaloch Campground – Olympic National Park",
    description: "Perched on ocean bluffs above wild Pacific Ocean beaches, where ancient rainforest meets the sea in Olympic National Park.",
    state: "WA", city: "Forks",
    lat: 47.6107, lon: -124.3736,
    hookupType: "dry", maxRvLength: 35, totalSites: 170,
    nightlyRateMin: 20, nightlyRateMax: 20,
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/232449",
    amenities: ["flush toilets", "dump station", "ocean beach access", "tide pools", "ranger programs"],
    campgroundType: "federal", imageUrl: null, phone: "360-962-2283",
  },
  {
    name: "Dash Point State Park",
    description: "A hidden gem in the Seattle metro area with nearly 2 miles of Puget Sound shoreline, crabbing, clamming, and easy city access.",
    state: "WA", city: "Federal Way",
    lat: 47.3218, lon: -122.4058,
    hookupType: "water_electric", maxRvLength: 35, totalSites: 138,
    nightlyRateMin: 30, nightlyRateMax: 45,
    bookingUrl: "https://washington.goingtocamp.com",
    amenities: ["dump station", "showers", "saltwater beach", "crabbing", "hiking trails"],
    campgroundType: "state", imageUrl: null, phone: "253-661-4955",
  },
  // Additional Oregon
  {
    name: "Cannon Beach RV Resort",
    description: "Full-service resort just minutes from iconic Haystack Rock, the Seaside Aquarium, and Oregon's most photographed beach town.",
    state: "OR", city: "Cannon Beach",
    lat: 45.8918, lon: -123.9615,
    hookupType: "full", maxRvLength: 70, totalSites: 100,
    nightlyRateMin: 45, nightlyRateMax: 85,
    bookingUrl: "https://www.cannonbeachrvresort.com",
    amenities: ["full hookups", "dump station", "showers", "pool", "laundry", "ocean nearby"],
    campgroundType: "private", imageUrl: null, phone: "503-436-2231",
  },
  {
    name: "Crater Lake National Park – Mazama Campground",
    description: "Camp inside the caldera rim of the deepest lake in the USA. At 5,909 feet elevation with dramatic volcanic scenery and stunning blue water.",
    state: "OR", city: "Crater Lake",
    lat: 42.8607, lon: -122.1526,
    hookupType: "dry", maxRvLength: 50, totalSites: 214,
    nightlyRateMin: 21, nightlyRateMax: 21,
    bookingUrl: "https://www.recreation.gov/camping/campgrounds/10088194",
    amenities: ["flush toilets", "dump station", "showers", "visitor center", "boat tours", "rim drives"],
    campgroundType: "federal", imageUrl: null, phone: "541-594-3000",
  },
  // Additional Idaho
  {
    name: "Dworshak State Park",
    description: "On one of the longest straight-axis dams in North America, with crystal-clear water, excellent fishing, and North Fork Clearwater canyon views.",
    state: "ID", city: "Orofino",
    lat: 46.6154, lon: -116.3074,
    hookupType: "full", maxRvLength: 60, totalSites: 105,
    nightlyRateMin: 20, nightlyRateMax: 35,
    bookingUrl: "https://idahostateparks.reserveamerica.com",
    amenities: ["full hookups", "dump station", "showers", "marina", "boat launch", "swimming beach"],
    campgroundType: "state", imageUrl: null, phone: "208-476-5994",
  },
  {
    name: "Twin Lakes Village RV Park",
    description: "On the shores of Lower Twin Lake in the Idaho Panhandle with easy access to Silverwood Theme Park, waterslides, and family fun.",
    state: "ID", city: "Rathdrum",
    lat: 47.8131, lon: -116.8946,
    hookupType: "full", maxRvLength: 65, totalSites: 120,
    nightlyRateMin: 38, nightlyRateMax: 58,
    bookingUrl: "https://www.twinlakesvillage.com",
    amenities: ["full hookups", "dump station", "showers", "pool", "boat launch", "lake swimming"],
    campgroundType: "private", imageUrl: null, phone: "208-687-1760",
  },
  // Additional Montana
  {
    name: "Cooney State Park",
    description: "A warm-water reservoir perfect for water skiing, fishing for walleye and rainbow trout, and watching spectacular Montana sunsets.",
    state: "MT", city: "Roberts",
    lat: 45.3566, lon: -109.0018,
    hookupType: "water_electric", maxRvLength: 40, totalSites: 75,
    nightlyRateMin: 16, nightlyRateMax: 28,
    bookingUrl: "https://stateparks.mt.gov",
    amenities: ["dump station", "showers", "boat launch", "swimming area", "water skiing", "fishing"],
    campgroundType: "state", imageUrl: null, phone: "406-962-3462",
  },
  {
    name: "Glacier Haven RV Park & Campground",
    description: "Family-owned campground in Columbia Falls with easy Glacier NP access, full hookups, and a welcoming community atmosphere.",
    state: "MT", city: "Columbia Falls",
    lat: 48.3736, lon: -114.1830,
    hookupType: "full", maxRvLength: 70, totalSites: 65,
    nightlyRateMin: 38, nightlyRateMax: 58,
    bookingUrl: "https://www.glacierhaven.com",
    amenities: ["full hookups", "dump station", "showers", "laundry", "fire rings", "Glacier NP nearby"],
    campgroundType: "private", imageUrl: null, phone: "406-892-2412",
  },
];

async function main() {
  console.log(`Seeding ${campgrounds.length} campgrounds...`);

  const inserted = await db
    .insert(campgroundsTable)
    .values(campgrounds)
    .onConflictDoNothing()
    .returning({ id: campgroundsTable.id });

  console.log(`Inserted ${inserted.length} campgrounds.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Error seeding campgrounds:", err);
  process.exit(1);
});
